# exampleSite 
#
# Requires the Hugo static site generator. https://gohugo.io/

baseURL = "http://yourwebsite.ca/"
languageCode = "en-us"
title = "hugo-smorg"
theme = "hugo-smorg"

[params]										# used in theme layout, override in your site's layout
logotype = '<span class="has-text-weight-bold">hugo<span class="has-text-danger">smorg</span></span>' # in partials/nav.html
fullname = "Your Full Or Organization Name"		# _default/single.html, partials/footer.html
canonifyurls = true


